### ISSUE TITLE
Create generic Gated build script for standard activity

### ISSUE THREAD

**Issue by susilparida** [k8-proxy/s-k8-buildpipeline#4]
A Gated build which will build our code and run tests on pull requests

- On the GitHub repo, go to Actions > New workflow > set up a workflow will be done by the respective repo editors. 
- Name the file as 'gated.yml'. 
- The Gated file code from the this repo will be inherited by respective repo. 
- Standardize to trigger unit tests, publishing code coverage.
         -  Generic way to trigger unit testing suites. 
         -  Generic way to trigger Integration testing suites.
         -  Publish code coverage at the time of code commit. 
         -  Keep provision to run security script check triggered during checkin.

**Comment by azopat** [comment]
Workflow (gated.yml) design  :
- Multiple job (one job per programming language). So according to the language being used, one job will be triggered.
- Each language job will have the following steps :  
   * Checkout code
  * Install the corresponding programming language runtime environment
  * Execute the test script. We will agree with devs a common path to the test script that will be executed
  * Publish code coverage
It will be triggered on each push.

**Comment by susilupwork** [comment]
Looks good.
